######################################################################
# Automatically generated by qmake (3.0) Fri Feb 21 03:10:34 2020
######################################################################

QT += network

TEMPLATE = app
TARGET = socket
INCLUDEPATH += .

# Input
HEADERS += myserver.h
SOURCES += main.cpp myserver.cpp
