######################################################################
# Automatically generated by qmake (3.0) Fri Feb 21 01:03:00 2020
######################################################################

QT += widgets

TEMPLATE = app
TARGET = clock
INCLUDEPATH += .

# Input
HEADERS += digitalclock.hpp
SOURCES += digitalclock.cpp main.cpp
