######################################################################
# Automatically generated by qmake (3.0) Sun Mar 8 00:39:04 2020
######################################################################

CONFIG += c++11
QT += network
QT += widgets
TEMPLATE = app
TARGET = client
INCLUDEPATH += .

# Input
HEADERS += myclient.h mytask.h
SOURCES += myclient.cpp mytask.cpp visualization_starter.cpp
